name: CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - run: yarn
      - run: yarn build

      - name: Deploy to xquare
        uses: team-xquare/xquare-deployment-action@master
        with:
          environment: prod
          access_key: ${{ secrets.XQUARE_ACCESS_KEY }}
          buildargs: |
            MYSQL_HOST=${{ secrets.DB_HOST }}
            MYSQL_USERNAME=${{ secrets.DB_USERNAME }}
            MYSQL_PASSWORD=${{ secrets.DB_PASSWORD }}
            REDIS_HOST=${{ secrets.REDIS_HOST }}
          yarn_docker_build: true
          yarn_workspace: '@service/eeats'
          base_path: .